# Generated by Django 4.2 on 2023-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banners_cache_time',
            field=models.PositiveIntegerField(default=10, verbose_name='время кэширования, минут'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(('value_type__in', ('fixed_amount', 'fixed_price')), models.Q(('value__gt', 0), ('value_type', 'percentage'), ('value__lt', 100), ('value_type', 'percentage')), _connector='OR'), name='check_value_percentage_in_discount', violation_error_message='Процент скидки не может быть менее 0 и более 100'),
        ),
        migrations.AddConstraint(
            model_name='discountoncart',
            constraint=models.CheckConstraint(check=models.Q(('value_type__in', ('fixed_amount', 'fixed_price')), models.Q(('value__gt', 0), ('value_type', 'percentage'), ('value__lt', 100), ('value_type', 'percentage')), _connector='OR'), name='check_value_percentage_in_discount_on_cart', violation_error_message='Процент скидки не может быть менее 0 и более 100'),
        ),
        migrations.AddConstraint(
            model_name='discountonset',
            constraint=models.CheckConstraint(check=models.Q(('value_type__in', ('fixed_amount', 'fixed_price')), models.Q(('value__gt', 0), ('value_type', 'percentage'), ('value__lt', 100), ('value_type', 'percentage')), _connector='OR'), name='check_value_percentage_in_discount_on_set', violation_error_message='Процент скидки не может быть менее 0 и более 100'),
        ),
    ]
