# Generated by Django 4.2 on 2023-06-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.offer', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ManyToManyField(through='order.OrderItem', to='shops.offer', verbose_name='предложение'),
        ),
    ]
