# Generated by Django 4.2 on 2023-07-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.offer', verbose_name='предложение'),
        ),
    ]
