# Generated by Django 4.2 on 2023-06-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'история просмотров',
                'verbose_name_plural': 'история просмотров',
            },
        ),
        migrations.CreateModel(
            name='HistorySearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_products', to='account.historysearch', verbose_name='история')),
            ],
            options={
                'verbose_name': 'история просмотра продукта',
                'verbose_name_plural': 'история просмотра продуктов',
            },
        ),
    ]
