# Generated by Django 4.2 on 2023-06-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysearchproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_products', to='products.product', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='historysearch',
            name='product',
            field=models.ManyToManyField(related_name='history', through='account.HistorySearchProduct', to='products.product', verbose_name='продукт'),
        ),
    ]
