# Generated by Django 4.2 on 2023-07-11 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_alter_shop_phone_number_alter_shop_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='ФИО получателя заказа')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', verbose_name='номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обнавлено')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('paid', 'Оплачено'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('canceled', 'Отменено')], default='created', max_length=20, verbose_name='статус')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('delivery_option', models.CharField(choices=[('Delivery', 'Обычная доставка'), ('Express Delivery', 'Экспресс-доставка')], max_length=20, verbose_name='способ доставки')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='адрес доставки')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='город доставки')),
                ('payment_option', models.CharField(choices=[('Online Card', 'Оналайн картой'), ('Another card', 'Оплата чужой картой')], max_length=20, verbose_name='способ оплаты')),
                ('comment', models.CharField(max_length=200, verbose_name='комментарий')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='итоговая цена')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.offer', verbose_name='предложение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказа',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ManyToManyField(through='orders.OrderItem', to='shops.offer', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
