# Generated by Django 4.2 on 2023-07-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.offer', verbose_name='предложение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ManyToManyField(through='orders.OrderItem', to='shops.offer', verbose_name='предложение'),
        ),
    ]
